version: '3'

networks:
  app-network:
    driver: bridge

services:
  contactsapi:
    image: contactsapi
    environment:
      - MONGO_HOST=mongodb
      - MONGO_PORT=27017
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "8081:80"
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - app-network
        
  mongodb:
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=
      - MONGO_INITDB_ROOT_PASSWORD=
    ports:
      - "27017"
    networks: 
      - app-network
      
      
